const Tags = [
  // Original Tags
  { name: "JavaScript", slug: "javascript", description: "The programming language of the web" },
  { name: "TypeScript", slug: "typescript", description: "Typed superset of JavaScript" },
  { name: "React", slug: "react", description: "A JavaScript library for building user interfaces" },
  { name: "Next.js", slug: "nextjs", description: "React framework for production applications" },
  { name: "Node.js", slug: "nodejs", description: "JavaScript runtime built on Chrome's V8 engine" },
  { name: "Python", slug: "python", description: "High-level programming language for general purpose programming" },
  { name: "Machine Learning", slug: "machine-learning", description: "AI application that provides systems the ability to learn" },
  { name: "API", slug: "api", description: "Application Programming Interface" },
  { name: "CSS", slug: "css", description: "Cascading Style Sheets for styling web pages" },
  { name: "HTML", slug: "html", description: "HyperText Markup Language for structuring web content" },
  { name: "Database", slug: "database", description: "Structured collection of data" },
  { name: "MongoDB", slug: "mongodb", description: "NoSQL database program" },
  { name: "PostgreSQL", slug: "postgresql", description: "Open source object-relational database" },
  { name: "Docker", slug: "docker", description: "Platform for developing, shipping, and running applications" },
  { name: "Kubernetes", slug: "kubernetes", description: "Container orchestration system" },
  { name: "AWS", slug: "aws", description: "Amazon Web Services cloud computing platform" },
  { name: "Azure", slug: "azure", description: "Microsoft's cloud computing platform" },
  { name: "GCP", slug: "gcp", description: "Google Cloud Platform" },
  { name: "DevOps", slug: "devops", description: "Combination of software development and IT operations" },
  { name: "Git", slug: "git", description: "Distributed version control system" },
  { name: "CI/CD", slug: "cicd", description: "Continuous integration and continuous delivery" },
  { name: "Testing", slug: "testing", description: "Software testing methodologies" },
  { name: "Jest", slug: "jest", description: "JavaScript testing framework" },
  { name: "GraphQL", slug: "graphql", description: "Query language for APIs" },
  { name: "REST", slug: "rest", description: "Representational state transfer architectural style" },
  { name: "UI/UX", slug: "ui-ux", description: "User interface and user experience design" },
  { name: "Performance", slug: "performance", description: "Optimization and performance improvement" },
  { name: "Security", slug: "security", description: "Application and system security" },
  { name: "WebSockets", slug: "websockets", description: "Bidirectional communication protocol over TCP" },
  { name: "Microservices", slug: "microservices", description: "Architectural style for software applications" },
  { name: "Serverless", slug: "serverless", description: "Cloud computing execution model" },
  { name: "Progressive Web Apps", slug: "pwa", description: "Web applications with native app-like features" },
  { name: "WebAssembly", slug: "webassembly", description: "Binary instruction format for web browsers" },
  { name: "Edge Computing", slug: "edge-computing", description: "Distributed computing paradigm" },

  // Frontend Frameworks & Libraries
  { name: "Vue.js", slug: "vuejs", description: "Progressive JavaScript framework for building UIs" },
  { name: "Angular", slug: "angular", description: "TypeScript-based web application framework" },
  { name: "Svelte", slug: "svelte", description: "Cybernetically enhanced web apps" },
  { name: "Solid.js", slug: "solidjs", description: "Declarative JavaScript library for building user interfaces" },
  { name: "Astro", slug: "astro", description: "Modern static site builder for faster websites" },
  { name: "Remix", slug: "remix", description: "Full-stack web framework built on React Router" },
  { name: "Qwik", slug: "qwik", description: "Resumable framework for instant-loading web apps" },

  // CSS Frameworks & Tools
  { name: "Tailwind CSS", slug: "tailwindcss", description: "Utility-first CSS framework" },
  { name: "Sass", slug: "sass", description: "CSS preprocessor with superpowers" },
  { name: "styled-components", slug: "styled-components", description: "CSS-in-JS styling solution" },
  { name: "PostCSS", slug: "postcss", description: "Tool for transforming CSS with JavaScript" },
  { name: "Bootstrap", slug: "bootstrap", description: "Popular CSS framework for responsive design" },
  { name: "Material UI", slug: "material-ui", description: "React components implementing Material Design" },
  { name: "Chakra UI", slug: "chakra-ui", description: "Simple, modular React component library" },

  // Backend & Runtime
  { name: "Deno", slug: "deno", description: "Secure TypeScript runtime built on V8" },
  { name: "Bun", slug: "bun", description: "Fast all-in-one JavaScript runtime" },
  { name: "Express.js", slug: "expressjs", description: "Minimal Node.js web application framework" },
  { name: "Fastify", slug: "fastify", description: "Fast and low overhead Node.js web framework" },
  { name: "NestJS", slug: "nestjs", description: "Progressive Node.js framework for scalable applications" },
  { name: "tRPC", slug: "trpc", description: "End-to-end typesafe APIs made easy" },
  { name: "Hono", slug: "hono", description: "Ultrafast web framework for the edge" },

  // Programming Languages
  { name: "Rust", slug: "rust", description: "Systems programming language focused on safety and performance" },
  { name: "Go", slug: "golang", description: "Statically typed compiled language by Google" },
  { name: "Java", slug: "java", description: "Object-oriented programming language" },
  { name: "C#", slug: "csharp", description: "Modern object-oriented programming language" },
  { name: "Swift", slug: "swift", description: "Powerful programming language for iOS and macOS" },
  { name: "Kotlin", slug: "kotlin", description: "Modern programming language for Android development" },
  { name: "PHP", slug: "php", description: "Server-side scripting language" },
  { name: "Ruby", slug: "ruby", description: "Dynamic, object-oriented programming language" },
  { name: "Elixir", slug: "elixir", description: "Functional, concurrent language for scalable applications" },
  { name: "Zig", slug: "zig", description: "General-purpose programming language and toolchain" },

  // Databases & Data
  { name: "Redis", slug: "redis", description: "In-memory data structure store" },
  { name: "MySQL", slug: "mysql", description: "Open-source relational database" },
  { name: "SQLite", slug: "sqlite", description: "Lightweight embedded database" },
  { name: "Supabase", slug: "supabase", description: "Open-source Firebase alternative" },
  { name: "Prisma", slug: "prisma", description: "Next-generation ORM for Node.js and TypeScript" },
  { name: "Drizzle", slug: "drizzle", description: "TypeScript ORM for SQL databases" },
  { name: "Elasticsearch", slug: "elasticsearch", description: "Distributed search and analytics engine" },
  { name: "Apache Cassandra", slug: "cassandra", description: "Distributed NoSQL database" },
  { name: "Neo4j", slug: "neo4j", description: "Graph database platform" },
  { name: "ClickHouse", slug: "clickhouse", description: "Column-oriented database for analytics" },

  // AI & Machine Learning
  { name: "TensorFlow", slug: "tensorflow", description: "Open-source machine learning framework" },
  { name: "PyTorch", slug: "pytorch", description: "Machine learning library based on Torch" },
  { name: "OpenAI", slug: "openai", description: "Artificial intelligence research and deployment" },
  { name: "LangChain", slug: "langchain", description: "Framework for developing LLM applications" },
  { name: "Hugging Face", slug: "huggingface", description: "AI community and model hub" },
  { name: "Computer Vision", slug: "computer-vision", description: "AI field for image and video understanding" },
  { name: "NLP", slug: "nlp", description: "Natural Language Processing techniques" },
  { name: "GPT", slug: "gpt", description: "Generative Pre-trained Transformer models" },
  { name: "Stable Diffusion", slug: "stable-diffusion", description: "Text-to-image generation model" },
  { name: "MLOps", slug: "mlops", description: "Machine learning operations practices" },

  // Mobile Development
  { name: "React Native", slug: "react-native", description: "Framework for building native mobile apps with React" },
  { name: "Flutter", slug: "flutter", description: "Google's UI toolkit for multi-platform apps" },
  { name: "SwiftUI", slug: "swiftui", description: "Declarative UI framework for Apple platforms" },
  { name: "Jetpack Compose", slug: "jetpack-compose", description: "Modern toolkit for building native Android UI" },
  { name: "Expo", slug: "expo", description: "Platform for building universal native apps" },
  { name: "Ionic", slug: "ionic", description: "Hybrid mobile app development framework" },

  // DevOps & Infrastructure
  { name: "Terraform", slug: "terraform", description: "Infrastructure as Code tool" },
  { name: "Ansible", slug: "ansible", description: "Automation tool for configuration management" },
  { name: "Jenkins", slug: "jenkins", description: "Open-source automation server" },
  { name: "GitHub Actions", slug: "github-actions", description: "CI/CD platform integrated with GitHub" },
  { name: "GitLab CI", slug: "gitlab-ci", description: "Continuous integration tool by GitLab" },
  { name: "Prometheus", slug: "prometheus", description: "Monitoring and alerting toolkit" },
  { name: "Grafana", slug: "grafana", description: "Observability and data visualization platform" },
  { name: "ArgoCD", slug: "argocd", description: "Declarative GitOps CD for Kubernetes" },
  { name: "Helm", slug: "helm", description: "Package manager for Kubernetes" },

  // Testing & Quality
  { name: "Cypress", slug: "cypress", description: "End-to-end testing framework" },
  { name: "Playwright", slug: "playwright", description: "Browser automation library" },
  { name: "Vitest", slug: "vitest", description: "Blazing fast unit test framework" },
  { name: "Selenium", slug: "selenium", description: "Browser automation framework" },
  { name: "Storybook", slug: "storybook", description: "UI component development environment" },
  { name: "ESLint", slug: "eslint", description: "JavaScript linting utility" },
  { name: "Prettier", slug: "prettier", description: "Opinionated code formatter" },

  // Blockchain & Web3
  { name: "Ethereum", slug: "ethereum", description: "Decentralized blockchain platform" },
  { name: "Solidity", slug: "solidity", description: "Smart contract programming language" },
  { name: "Web3.js", slug: "web3js", description: "Ethereum JavaScript API" },
  { name: "IPFS", slug: "ipfs", description: "Distributed file storage protocol" },
  { name: "Smart Contracts", slug: "smart-contracts", description: "Self-executing blockchain contracts" },
  { name: "DeFi", slug: "defi", description: "Decentralized finance applications" },
  { name: "NFT", slug: "nft", description: "Non-fungible tokens and digital assets" },

  // Emerging Technologies
  { name: "Quantum Computing", slug: "quantum", description: "Computing using quantum-mechanical phenomena" },
  { name: "AR/VR", slug: "ar-vr", description: "Augmented and Virtual Reality technologies" },
  { name: "IoT", slug: "iot", description: "Internet of Things connected devices" },
  { name: "5G", slug: "5g", description: "Fifth generation mobile networks" },
  { name: "Robotics", slug: "robotics", description: "Design and operation of robots" },
  { name: "Blockchain", slug: "blockchain", description: "Distributed ledger technology" },
];

export default Tags;